version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: videoplayer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: videoplayer
      DB_USER: postgres
      DB_PASSWORD: password
      SESSION_SECRET: your-very-secure-session-secret-here
      NODE_ENV: production
      PORT: 3000
      UPLOAD_PATH: /app/uploads
      MAX_FILE_SIZE: 1073741824
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  uploads_data:
